### ISSUE TITLE
New version or build instruction

### ISSUE THREAD

**Issue by nickclasener** [loganhenson/tlint-plugin#1]
I'm running phpstorm 2018.3
I've tried updating it myself but it didn't work, my knowledge of java is lacking.

When you have the time could you write the steps of updating/building the plugin?

**Comment by loganhenson** [comment]
Hey @nickclasener, thanks for bringing this to my attention! I've submitted the new build, and you can view the PR (https://github.com/loganhenson/tlint-plugin/pull/2) for what exactly I updated. It should be live in the marketplace soon. https://plugins.jetbrains.com/plugin/10703-tlint

I'll try to get a more detailed build guide up soon!
