### ISSUE TITLE
error running tlint inspection: no tlint excutable found

### ISSUE THREAD

**Issue by shaband** [loganhenson/tlint-plugin#15]
i have a tlint install globally on composer  on ubunut 20 
and i using phpstrom 2020.2.2 when when in open a file  plugin failed to get  excutable tlint  as pics 

![image](https://user-images.githubusercontent.com/28789948/95724270-7398cc80-0c76-11eb-8cd1-08807dd9c727.png)

![image](https://user-images.githubusercontent.com/28789948/95723341-57e0f680-0c75-11eb-8e35-54716ca9f9e8.png)

**Comment by RalphMRivera** [comment]
Did you install tlint globally in the Ubuntu environment or where you are running PhoStorm? tlint must be installed globally on the same layer running PhpStorm.

In my case, I am running my app in a Vagrant box. Tlint is installed globally on my Mac which is where I am running PhpStorm and accessing the file system locally to reach for the app files. Tlint is not installed inside the Vagrant box.

**Comment by loganhenson** [comment]
the plugin looks in 2 places for tlint:

1. phpstorm's current working directory (project directory)/vendor/bin/tlint (this is the per project installation method)
2. your home directory/vendor/bin/tlint (this is the global installation method)

You can check where you have it installed by running `which tlint`, let me know if you are still having issues (and be sure to provide the output from `which tlint`)

**Comment by shaband** [comment]
thx  @loganhenson 

when  i run  ```$ which tlint ```

 it shows me the path was  
 ``` /home/shaband/.config/composer/vendor/bin/tlint ```

but it works after  i add it locally on my project using  

``` $ composer  require tightenco/tlint --dev  ```

**Comment by fgiorgio** [comment]
Same problem:
`Error running TLint inspection: No tlint executable found.`

```
$ which tlint
~/.config/composer/vendor/bin/tlint
```

Installed both globally and locally.
PHPStorm 2021.2.3
