### ISSUE TITLE
The tlint plugin is not working in PhpStorm 2020.3

### ISSUE THREAD

**Issue by RalphMRivera** [loganhenson/tlint-plugin#16]
The tlint plugin is not working in PhpStorm 2020.3

`Plugin error: Plugin 'TLint' (version '1.2.0') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is PS-203.5981.175`

I would love to help on this, but I don't know my way around Gradle.

**Comment by loganhenson** [comment]
TLin plugin v1.2.1 is live, you should be good to go @RalphMRivera !
