### ISSUE TITLE
I have this bug: java.lang.IllegalArgumentException: tlint path doesn't exist

### ISSUE THREAD

**Issue by nickclasener** [loganhenson/tlint-plugin#5]
I can't find where to add the path to Tlint, so in my eyes there are to options to solve it.
1. Is Clean a rebuild that when Linux `~/.config/composer/vendor/bin/tlint`
2. Is dirty `ln -s` the tlint to where ever Tlint-plugin looks

What OS are you running, and where does your composer resides?

**Comment by loganhenson** [comment]
This is something that needs improvement for other OS (Which I don't use regularly). Tighten devs primarily use OSX on dev machines, so it is currently setup to default to `~/.composer/vendor/bin/tlint` from the composer global installation.

**Comment by nickclasener** [comment]
My home is the same. 
I think i have to set my $JAVA_HOME for `System.getProperty("user.home")` to find it.

**Comment by loganhenson** [comment]
Did setting your $JAVA_HOME resolve your issue @nickclasener ? Sorry for the late response!

**Comment by danijelk** [comment]
Would it be possible to add a bin path check? Or an option so set path in phpstorm? 

Since we added tlinter to our project with composer require --dev as it should be.

**Comment by loganhenson** [comment]
@danijelk Yes this is on the todo list! (both checking and adding the config option, potentially a config option as well)

**Comment by randohinn** [comment]
Anything on this? Same error appears for Windows 10 as well..

**Comment by loganhenson** [comment]
@randohinn @danijelk I've uploaded a new version of the plugin that first checks for a local bin version of `tlint`, then falls back to a global version, and finally notifies the user there is no executable to be found. (It may be up to ~24hr before the plugin is published, `v1.1.3`)

**Comment by danijelk** [comment]
Seems to work as expected, thanks for that

**Comment by randohinn** [comment]
> @randohinn @danijelk I've uploaded a new version of the plugin that first checks for a local bin version of `tlint`, then falls back to a global version, and finally notifies the user there is no executable to be found. (It may be up to ~24hr before the plugin is published, `v1.1.3`)

Can't seem to find the global tlint on my machine though...
