### ISSUE TITLE
Logic for UseConfigOverEnv incorrect

### ISSUE THREAD

**Issue by danijelk** [loganhenson/tlint-plugin#9]
The plugins should consider if the actual file getting scanned is within the /config folder, as this is where they should be stored and used.

![Image 2019-10-18 at 11 15 38 AM](https://user-images.githubusercontent.com/580753/67082051-a3fb7700-f198-11e9-88ef-dfca7ea1e467.png)

**Comment by loganhenson** [comment]
@danijelk this is fixed in the cli (which this plugin uses), please update to `tightenco/tlint` v3.0.3
